### ISSUE TITLE
use prop-types package from npm

### ISSUE THREAD

**Issue by paulbrie** [cluj-javascripters/jsheroes-2018#1]
```
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
```

**Comment by gagyibenedek** [comment]
Is someone working on this? @romikette?

**Comment by romikette** [comment]
If i remember well I hade that covered, just forgot to close this thread.

**Comment by alexnm** [comment]
I took over parts of the repo to get the website up and running for 2018, but I will need help with some of the features. We should have some more github issues soon
