### ISSUE TITLE
I can help fon 2019 site :)

### ISSUE THREAD

**Issue by jeremenichelli** [cluj-javascripters/jsheroes-2018#119]
Sorry that I'm opening an issue but I didn't know how to reach the team honestly.

I attended to JSHeroes past weekend and saw you needed help with the site, I wanted to speak to Alex Moldovan (@alexnm) but couldn't find him as he was super busy.

Feel free to DM me at twitter (https://twitter.com/jeremenichelli) so we can follow up the conversation, I have some ideas already :)

**Comment by alexnm** [comment]
Hi @jeremenichelli, no worries this is the perfect spot for this. I was indeed busy at the conf, but just as a reference for the future, I'm highly approachable and I love exchanging ideas with people on the hallway :)

We would love to get some help for the website, we also have a bunch of ideas to make it like a long term platform, would be great to get your ideas in there as well. I'll ping you twitter. @danielmocan can chime in here as well, he has a bunch of ideas for the website moving forward
