### ISSUE TITLE
Add the links to 2018/2017 in the header

### ISSUE THREAD

**Issue by alexnm** [cluj-javascripters/jsheroes-2018#143]
Would be nice especially when we don't have too much content for the next year, to have the links to previous years closer to the initial viewport

**Comment by alexnm** [comment]
reopening this as the links are not pointing ok. 2018 link should be relative /2018, 2017 link should be absolute to the old 2017.jsheroes.io website

**Comment by alexnm** [comment]
also putting this high priority since it doesn't work on the live website

**Comment by claudmi** [comment]
Attached: 
- mockups for desktop & mobile
- SVGs for drop-down arrows
Let's call it Prior Events (same as in Footer).

![mockups-header-prior-events](https://user-images.githubusercontent.com/210512/43963534-36f35a36-9cc3-11e8-9957-9229ace723a2.jpg)

[drop-down-arrows.zip](https://github.com/cluj-javascripters/jsheroes-2018/files/2278248/drop-down-arrows.zip)
