### ISSUE TITLE
Schedule is not showing correctly 

### ISSUE THREAD

**Issue by danielmocan** [cluj-javascripters/jsheroes-2018#150]
We need to fix the schedule component ui issues.  
![screen shot 2018-07-31 at 16 35 08](https://user-images.githubusercontent.com/15091326/43462867-e92d2b8c-94df-11e8-8103-3a8bc398d8ae.png)

**Comment by lirantal** [comment]
is this better?
![image](https://user-images.githubusercontent.com/316371/43864212-c57747b6-9b67-11e8-8eb7-0baa3324acfc.png)

![image](https://user-images.githubusercontent.com/316371/43864222-ccd878ea-9b67-11e8-848e-fe7b526b2a42.png)

**Comment by lirantal** [comment]
Also, I labeled as high-priority as this is currently happening in prod

**Comment by muresanalex** [comment]
@lirantal you can have it.
