### ISSUE TITLE
Add Women in Tech Cluj as community partners

### ISSUE THREAD

**Issue by alexnm** [cluj-javascripters/jsheroes-2018#158]
@oana-sipos can provide the logo/url so we can place it on the website

**Comment by lirantal** [comment]
@oana-sipos I couldn't find any official image on google or on your twitter, and the closest thing I could find to a website is the meetup group or the facebook group.

Let me know what to put as content and I'll be happy to apply it quickly.

**Comment by oana-sipos** [comment]
https://github.com/cluj-javascripters/jsheroes-2018/pull/164

**Comment by lirantal** [comment]
![image](https://user-images.githubusercontent.com/316371/43990039-398c83f8-9d5e-11e8-8760-3d3bd973f247.png)

@oana-sipos, right now I'm linking to the meetup group.
Do you want me to use a different link?
