### ISSUE TITLE
Add Hotjar tracking code

### ISSUE THREAD

**Issue by aleretegan** [cluj-javascripters/jsheroes-2018#23]
Please add the following tracking code in each page's <head>:

<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:716394,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>

**Comment by alexnm** [comment]
the script is now in master, it will be deployed with the first occasion
