### ISSUE TITLE
Add sponsor`s logo

### ISSUE THREAD

**Issue by aleretegan** [cluj-javascripters/jsheroes-2018#31]
![telenav](https://user-images.githubusercontent.com/19417706/34297350-4eb1a0dc-e720-11e7-9166-2e4a0fcc38db.png)

**Comment by alinilea** [comment]
Should I upload this url: https://www.telenav.com/home ?

**Comment by oana-sipos** [comment]
I would say even https://www.telenav.com/

**Comment by alinilea** [comment]
Updated Telenav's link to https://www.telenav.com/
