### ISSUE TITLE
Back button problem

### ISSUE THREAD

**Issue by alexnm** [cluj-javascripters/jsheroes-2018#46]
When you navigate from the root page to a speakers page and you click back, the url changes, but the content stays the same. No errors in the console. We need to investigate next's router for this.

**Comment by danielmocan** [comment]
@alexnm I tried to reproduce this but no luck. Can you please double check so we can close this ticket.

**Comment by alexnm** [comment]
@danielmocan try going to a speakers page when you are on the main page without the `/#speakers` hashtag. it still reproduces

**Comment by coredia** [comment]
This happens also when you click on "Adopt a Javascripter couch-surfing program" link form HomePage/News section, but it doesn't happen when you click on the same link from Footer (I will add this link on footer today, because we need it).

**Comment by alinilea** [comment]
This happens also when you click on "Adopt a Javascripter couch-surfing program" link form HomePage/News section, but it doesn't happen when you click on the same link from Footer (I will add this link on footer today, because we need it).

**Comment by raduGaspar** [comment]
Downgrade or upgrade next package. works fine with older versions... tested with a really old version (v2.4.9)

**Comment by alinilea** [comment]
Thank you for your help, @raduGaspar :) We will upgrade Nextjs and see how it works.

**Comment by alexnm** [comment]
with the new anchors, it appears that this is fixed
