### ISSUE TITLE
uncaught error on mouse over (speaker)

### ISSUE THREAD

**Issue by paulbrie** [cluj-javascripters/jsheroes-2018#54]
![image](https://user-images.githubusercontent.com/3997538/34910495-62ba47a4-f8bf-11e7-8315-f1bb915b5594.png)

**Comment by alexnm** [comment]
done.

cc @danielmocan the prefetch needs to be set on the actual next url, not the url mask we're using: https://github.com/cluj-javascripters/jsheroes-2018/commit/f2e4fb48e60c572f65c6357c3705c87fe7319c5b
