### ISSUE TITLE
Update News section for Adopt a Javascripter programme

### ISSUE THREAD

**Issue by aleretegan** [cluj-javascripters/jsheroes-2018#56]
Add in News section, at the end (after Tickets) text for Adopt a Javascripter:
- bolded text: Adopt a Javascripter
- text: If you want to be "adopted" by one of our Cluj Javascripters during the JSHeroes conference, you can use our Adopt a Javascripter couch-surfing program.
Subscribe as a Guest here. (Link: TBA )
Subscribe as a Host here. (Link: TBA)

**Comment by claudmi** [comment]
@aleretegan Please modify this issue by adding:

Insert a link to jsheroes.io/adopt-a-jser in the text:
... you can use our <a href="https://jsheroes.io/adopt-a-jser">Adopt a JavaScripter</a> couch-surfing program.
