### ISSUE TITLE
Create new page for 'Adopt a JavaScripter' Pairing program & Contest

### ISSUE THREAD

**Issue by claudmi** [cluj-javascripters/jsheroes-2018#59]
Create a new page (could be called .../adopt-a-jser).
I attached design mockup for desktop & mobile.
Also attached the photos used.
**FYI: The Contest part should be display: hidden until we are ready to start the contest.**

**Text for the Adopt program:**
If you want to be "adopted" by one of our Cluj JavaScripters during the JSHeroes conference, you can use our "Adopt a JavaScripter" couch-surfing program.

We will pair you up with a Host or a Guest that we think is ok for you, according to the info you filled in the application forms.
Apply below if you want to be a Guest, or if you are from Cluj-Napoca apply to be a Host.

**Text for the Adopt contest (may be modified later):**
JSHeroes 
PHOTO CONTEST

You are participating in the “Adopt a JavaScripter” couch-surfing 
program? Then enter the JSHeroes photo contest for a chance
to win 2 free tickets to the 2019 JSHeroes conference.

How does the contest work?

Take a photo with yourself and your Host or Guest when you meet them.
Then post it on Twitter with the hashtag #adoptajavascripter.
The winner will be selected randomly using random.org.
Post your photos until April 20, 2018.

Pretty simple!

![adopt_page](https://user-images.githubusercontent.com/210512/34938774-32a6bcc6-f9f2-11e7-9ee1-cf24a06e3b8d.png)
![adopt_mobile](https://user-images.githubusercontent.com/210512/34938783-36e7eabc-f9f2-11e7-909d-23108f66b828.png)

![asset-adopt-sky](https://user-images.githubusercontent.com/210512/34938750-1dfdd476-f9f2-11e7-9764-1993ddafa58f.jpg)
![asset-1010x1010-adopt-contest](https://user-images.githubusercontent.com/210512/34938751-1e312ca4-f9f2-11e7-9db8-ca90fae4f922.jpg)

**Comment by oana-sipos** [comment]
Stupid question, but how can they take a picture with their host/guest if they are not physically close by...? 🤔

**Comment by claudmi** [comment]
când se întâlnesc ei prima dată : ) cred
o sa mai edităm textul oricum

**Comment by alexnm** [comment]
I think the tickets were ment for JSHeroes 2019 :)

**Comment by alexnm** [comment]
@alinilea are you actively working on this page?

**Comment by alinilea** [comment]
@alexnm I'm sorry for the delay! I will complete the page ASAP. Thanks!
