### ISSUE TITLE
Change Evozon logo

### ISSUE THREAD

**Issue by aleretegan** [cluj-javascripters/jsheroes-2018#65]
Evozon changed their logo. The new one is: https://www.evozon.com/wp-content/uploads/2018/02/evozon-2018-white-logo-e1517932955835.png

**Comment by danielmocan** [comment]
@aleretegan 
If we change it it looks like this:

<img width="566" alt="screen shot 2018-02-10 at 22 19 30" src="https://user-images.githubusercontent.com/15091326/36066360-ba1644ce-0eb0-11e8-80e8-3724d55883eb.png">

**Comment by alexnm** [comment]
After discussing with @aleretegan we decided to keep the current logo
