### ISSUE TITLE
Change header section

### ISSUE THREAD

**Issue by aleretegan** [cluj-javascripters/jsheroes-2018#9]
-Check the dimensions; if they're not ok please come back with a comment so we adjust them.
-Auto-hide header on scroll down
![header_2000pxwidth](https://user-images.githubusercontent.com/19417706/32992776-82067242-cd57-11e7-8431-f57c5c097274.png)

**Comment by gagyibenedek** [comment]
I'll jump on this later this week if that's not too late.

**Comment by alexnm** [comment]
go for it :)

**Comment by alexnm** [comment]
@gagyibenedek will you work on this? if not someone else should assign itself to it

**Comment by gagyibenedek** [comment]
I'd like to but won't have the time for a few more days. If somebody wants to take it just comment here, and I'll be glad to give it up.

**Comment by alexnm** [comment]
@alinilea please check the header styling on mobile is possible
